# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool: k8s
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        command: 'login'
      
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'arfront/video-encoder'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          latest